### ISSUE TITLE
how to get client id?

### ISSUE THREAD

**Issue by toshibochan** [magaHH/homebridge-bmw-connected-accessories#5]
how to get client id?

**Comment by toshibochan** [comment]
my car is Mini Cooper

**Comment by jackklink** [comment]
I am also trying to figure this out. The old method of finding it via the BMW connected website no longer works as that website no longer is offered from BMW. Someone else mentioned to use the client ID that is listed in the example on the README, but that also does not work and throws an error and also crashes Homebridge entirely!

[9/13/2021, 12:24:48 PM] [BMW i3 Unlock] Sending Command RDU
[9/13/2021, 12:24:48 PM] [BMW i3 Unlock] Now   :1631561088418
[9/13/2021, 12:24:48 PM] [BMW i3 Unlock] Later :0
[9/13/2021, 12:24:48 PM] [BMW i3 Unlock] Getting Auth Token
[9/13/2021, 12:24:49 PM] [BMW i3 Unlock] null
[9/13/2021, 12:24:49 PM] TypeError: Cannot read property 'split' of null
    at BMWConnectedAccessory.<anonymous> (/usr/lib/node_modules/homebridge-bmw-connected-accessories/index.js:261:23)
    at Request.self.callback (/usr/lib/node_modules/homebridge-bmw-connected-accessories/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-bmw-connected-accessories/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-bmw-connected-accessories/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[9/13/2021, 12:24:49 PM] Got SIGTERM, shutting down Homebridge...

**Comment by ggiese2000** [comment]
Hi - Almost 2 years later I am experiencing the same issue.
Anything that can be done? 
Can I help?

**Comment by AdeTheux** [comment]
> Hi - Almost 2 years later I am experiencing the same issue. Anything that can be done? Can I help?

I've seen a few recent [libraries](https://github.com/topics/bmw-connecteddrive) but nothing that works with Homebridge. The different HB for BMW plugins that exist haven't been updated in years and none have work for a while now.

**Comment by ggiese2000** [comment]
maybe this becomes an option?
[https://bmw-cardata.bmwgroup.com/thirdparty/public/home](url)

**Comment by AdeTheux** [comment]
> https://bmw-cardata.bmwgroup.com/thirdparty/public/home

Maybe but this is way above my knowledge 😅
I just seem to remember reading that there are also different options possible based on the iDrive version, and so the MY of the car, and whether it's an EV or not.
